"""add wishlists

Revision ID: 49b04200bbd5
Revises: 6e13f329329b
Create Date: 2020-10-01 16:40:37.450687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b04200bbd5'
down_revision = '6e13f329329b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_student', sa.Boolean(), nullable=True))
    op.drop_constraint('users_wishlist_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'wishlists', ['wishlist_id'], ['id'])
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_wishlist_id_fkey', 'users', 'departments', ['wishlist_id'], ['id'])
    op.drop_column('users', 'is_student')
    # ### end Alembic commands ###
