"""first migration

Revision ID: 77a0c2e972c5
Revises: 
Create Date: 2020-10-02 08:55:27.200109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a0c2e972c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wishlist_user_id_fkey', 'wishlist', type_='foreignkey')
    op.drop_column('wishlist', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('wishlist_user_id_fkey', 'wishlist', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
