"""added profile pic path

Revision ID: 9d8871ea6143
Revises: 
Create Date: 2020-10-02 02:33:04.511886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d8871ea6143'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic_path', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('wishlists')
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.drop_constraint('users_wishlist_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'wishlist', ['wishlist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_wishlist_id_fkey', 'users', 'wishlists', ['wishlist_id'], ['id'])
    op.drop_column('users', 'profile_pic_path')
    op.create_table('wishlists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wishlists_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wishlists_pkey')
    )
    op.drop_table('profile_photos')
    op.drop_table('wishlist')
    # ### end Alembic commands ###
