"""remove unique

Revision ID: d0f99f5f360c
Revises: 61873b4920a8
Create Date: 2020-09-30 18:00:49.244605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f99f5f360c'
down_revision = '61873b4920a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_name_key', 'role', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('role_name_key', 'role', ['name'])
    # ### end Alembic commands ###
